### ISSUE TITLE
Error generating type with design-time visible attribute

### ISSUE THREAD

**Issue by Therzok** [HavenDV/DependencyPropertyGenerator#1]
### Describe the bug

Cool project, thank you for creating something like this!

Type isn't generating correctly when a partial handler for dependency property exists and `[DesignTimeVisible(false)]` is set:

```
Error	DPG001	System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.	
```

If the attribute has no parameters, this is the error instead:
```
Error	DPG001	System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
```

### Steps to reproduce the bug

```csharp
[DependencyProperty("Text", typeof(string))]
[DesignTimeVisible(false)]
public partial class Generatable : FrameworkElement
{
    partial void OnTextChanged(string oldValue, string newValue)
    {
    }
}
```
or
```csharp
[DependencyProperty("Text", typeof(string))]
[DesignTimeVisible]
public partial class Generatable : FrameworkElement
{
    partial void OnTextChanged(string oldValue, string newValue)
    {
    }
}
```

### Expected behavior

It generates

### NuGet package version

0.34.1

### IDE

Visual Studio 2022

**Comment by Therzok** [comment]
Most likely caused by this, but not sure: https://github.com/HavenDV/DependencyPropertyGenerator/blob/edb9680c9f2c786bd6516c0556cdd0e199810190/src/libs/DependencyPropertyGenerator/DependencyPropertyGenerator.cs#L182-L184

**Comment by Therzok** [comment]
Also, it might be useful to have a `Compilation.GetTypeByMetadataName()` for your generatable attributes at the top, to avoid running the generator on projects that reference the package transitively, but don't actually use the attributes.

And then you can probably just check the actual types with the `AttributeClass` type.

**Comment by HavenDV** [comment]
Thanks for the problem and details. This is weird, I solved a similar problem with the ComVisible attribute next to it, and I thought I fixed those problems as a class.

> Also, it might be useful to have a `Compilation.GetTypeByMetadataName()` for your generatable attributes at the top, to avoid running the generator on projects that reference the package transitively, but don't actually use the attributes.
> 
> And then you can probably just check the actual types with the `AttributeClass` type.

I don't quite understand you here. The generator contains the MSBuild property `<DevelopmentDependency>true</DevelopmentDependency>` which, when set, will create the following PackageReference:
```xml
<PackageReference Include="DependencyPropertyGenerator" Version="0.34.1">
       <PrivateAssets>all</PrivateAssets>
       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```
That is, the generator will not be transitively available to projects that refer to the project with the generator, and will not be run in them.
I may be wrong and misunderstanding something, my experience with Roslyn is quite limited

**Comment by HavenDV** [comment]
I added tests for your case and fixed the issue. I also noticed a problem if you use a declaration without Generic attributes, I also fixed it.
