### ISSUE TITLE
IDE0600 warning

### ISSUE THREAD

**Issue by virzak** [HavenDV/DependencyPropertyGenerator#2]
### Describe the bug

`oldValue` and `newValue` might not be used in 

```cs
static partial void OnPropertyChanged (T sender, int oldValue, int newValue)
```

### Steps to reproduce the bug

Implement the examples in the readme file

### Expected behavior

There needs to be a way to opt out of that generation. Either by default or explicitly. Here are some options:
- `GenerateOldValue = true`
- `SkipOldValue = true`
- `GenerateParameters = Gen.OldValue | Gen.NewValue`

Alternatively use [suppressor](https://github.com/PathogenPlayground/DiagnosticSuppressorTest) to suppress this warning.

### Screenshots

![image](https://user-images.githubusercontent.com/6209775/177841620-8b108a40-9f36-45a4-a8a9-b8d2e56be48c.png)

### NuGet package version

 0.34.3

### IDE

Visual Studio 2022-preview

**Comment by HavenDV** [comment]
I don't want to add an extra parameter to an attribute just for this. It might be worth adding partial declarations with one parameter (which will be newValue) and no parameters. The compiler itself will cut out calls to partial methods without definition.

**Comment by virzak** [comment]
Cool. `newValue` is often not used either. Especially when `AffectRender` is used and all we want ro do is invalidate.

**Comment by HavenDV** [comment]
Update has been released, please check

**Comment by virzak** [comment]
Thanks!

I can work with this, but there are issues.

OnPropertyChanged can no longer be `virtual`. Turns out that this was the case in my project and I'm not sure how many more would face the same issue.

The pattern I have to use is:

```cs
partial void OnSensitivityChanged() => OnVirtualSensitivityChanged();
protected virtual void OnVirtualSensitivityChanged() { }
```

I wonder whether the code generator can look into the existing code base and call the one method which matches one of several predetermined patterns.

- OnPropertyChanged(T <somevar1>, T <somevar2>)
- OnPropertyChanged(T <somevar1>)
- OnPropertyChanged()

That way the user is at liberty to use any variable names. `T sender` would mean that most users will need to rewrite code if they used the established [pattern](https://github.com/dotnet/wpf/blob/b63c69eaf5b58e758765a37bb18064bbc94832ad/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBlock.cs#L3556):

```cs
TextBlock textBlock = sender as TextBlock;
```

Perhaps a method name can be optionally specified using a property `OnChanged = nameof(NonStandardPropertyChanged)`. That's how communitytoolkit MVVM [code generator](https://github.com/CommunityToolkit/dotnet/issues/8) works.

**Comment by HavenDV** [comment]
> OnPropertyChanged can no longer be `virtual`. Turns out that this was the case in my project and I'm not sure how many more would face the same issue.

I don't think many people use it. [I can't add the virtual modifier by default because that would force the user to always define partial methods.](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/partial-method). In any case, I will follow the reaction of people on this issue.

> That way the user is at liberty to use any variable names. `T sender` would mean that most users will need to rewrite code if they used the established [pattern](https://github.com/dotnet/wpf/blob/b63c69eaf5b58e758765a37bb18064bbc94832ad/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBlock.cs#L3556):

In the latest patch, the name will follow this pattern.

> Perhaps a method name can be optionally specified using a property OnChanged = nameof(NonStandardPropertyChanged). That's how communitytoolkit MVVM https://github.com/CommunityToolkit/dotnet/issues/8 works.

At the moment I'm not sure about this, there are many nuances here

**Comment by virzak** [comment]
The way I see the advantages of looking into user code:
- Allowing `virtual`
- Allowing non standard variable names
- Cleaner code generator, which isn't probing multiple signatures

But that's a separate issue. IDE0600 warning is now resolved.

**Comment by HavenDV** [comment]
It's all possible, but I'm afraid to overcomplicate the attribute with a large number of parameters. Unfortunately, it is impossible to move such specific parameters into a separate class of settings and pass them when necessary, because attribute parameters cannot be a complex type

**Comment by virzak** [comment]
`OnChanged` property doesn't even need to be added though. In my project I wouldn't need it at all since I'd name all my functions properly.

If the generator finds an OnPropertyChanged(), it just call it, regardless whether it is virtual or how many parameters it has, as long as it matches the allowed signatures.

**Comment by HavenDV** [comment]
Maybe I should explain how it works now:
The generator doesn't look at your code except for attributes (and is only called when attributes change). Based on this, it generates partial declarations for methods that the user can override. If it doesn't, then the compiler will strip these partial declarations and the code that calls them from the compilation. But this only works for partial declarations without modifiers.

Of course, I can go through the entire user code looking for the necessary OnPropertyChanged methods, but this will be much slower and less obvious to the user (because the IDE usually helps with the definition of partial declarations).

**Comment by virzak** [comment]
Got it. I'm not entirely sure what the speed difference would be, but the community mvvm does [generate](https://github.com/CommunityToolkit/dotnet/blob/d3250b6f789e86338646c23d72411636f717625d/CommunityToolkit.Mvvm.SourceGenerators/Input/RelayCommandGenerator.Execute.cs#L182-L212) code based on the user signature.

I'm using it extensively and even if it is slower than this code generator, I haven't felt it. Complexity seems to be the same to me.

**Comment by HavenDV** [comment]
I'm sorry, but I'm still not entirely sure about this. We can create a separate issue for this and see if other users need it.
