### ISSUE TITLE
[DependencyProperty<int?>("Property")] doesn't compile

### ISSUE THREAD

**Issue by virzak** [HavenDV/DependencyPropertyGenerator#4]
### Describe the bug

Can't compile

### Steps to reproduce the bug

Mark class with [DependencyProperty<int?>("Property")]

**Comment by HavenDV** [comment]
[Fixed in 0.52.1](https://github.com/HavenDV/DependencyPropertyGenerator/commit/c472da636dce6279f1403b725e116a343d753b8b)
